import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    en: {
        loggingOut: "Logging you out",
        Home: "Home",
        Hello: "Hello",
        Register: "Register",
        logout: "Logout",
        Rides: "Rides",
        Ride: "Ride",
        Settings: "Settings",
        paymentStatus: "Payment Status",
        totalDistance: "Total Distance",
        boardingPoint: "Boarding Point",
        droppingPoint: "Dropping Point",
        yourRides: "Your Rides",
        distance: "Distance",
        duration: "Duration",
        editEmail: "Edit E-Mail",
        subscriptions: "Subscriptions",
        subscription: "Subscription",
        price: "Price",
        renewable: "Renewable",
        after: "After",
        days: "days",
        description: "Description",
        callSupport: "Call Support",
        others: "Others",
        driverMode: "Driver Mode",
        userMode: "User Mode",
        at: "at",
        meterShort: "M",
        kilimeterShort: "KM",
        fare: "Fare",
        cash: "Cash",
        Card: "Card",
        book: "Book",
        bookRide: "Book Ride",
        Time: "Time",
        paymentMethod: "Payment Method",
        rideBooked: "Ride Booked",
        rideCompleted: "Ride completed",
        paymentMarked: "Payment Marked",
        onTheWay: "On the way",
        navigateToRider: "Navigate to Rider",
        startRide: "Start Ride",
        finishRide: "Finish Ride",
        bookingID: "Booking ID",
        paymentReceived: "Payment Received",
        rideNotFinished: "Ride is not finished yet!",
        verifyYourEmailAddress: "Visit the following link to verify your email address.",
        confirm: "Confirm",
        on: "on",
        planNotFound: "Plan not found!",
        shouldContainOnlyAlphabets: "Should contain only alphabets",
        shouldContainOnlyNumbers: "Should contain only numbers",
        subscriptionPlansNotAvailable: "No subscription plans available!",
        seeNewRequests: "See new Requests",
        cancelRequest: "Cancel Request",
        subscribe: "Subscribe",
        unableToStartTheRide: "Unable to start the ride!",
        unableToGetSubscriptions: "Unable to get subscriptions!",
        unableToGetPlans: "Unable to get plans!",
        unableToSubscribe: "Unable to subscribe!",
        planSubscribed: "Plan Subscribed!",
        unableToFinishTheRide: "Unable to Finish the ride!",
        unabletoAcceptTheRide: "Unable to accept the ride!",
        unableToGetBooking: "Unable to get booking!",
        rideNotFinishedYet: "Ride not finished yet!",
        waitingForNearbyDriversToAcceptYourRideRequest: "Waiting for nearby drivers to accept your ride request",
        driverAcceptedYourRideRequest: "Driver accepted your ride request",
        unableToFetchDriversNearby: "unable to fetch drivers nearby",
        unableToFetchYourCurrentLocation: "Unable to fetch your current location",
        directionsRequestFailedDueTo: "Directions request failed due to",
        unableToCreateRequest: "Unable to create request!",
        unableToCancelRequest: "unable to cancel request",
        unableToMarkPaymentForTheRide: "Unable to mark payment for the ride!",
        emailVeried: "Congrats...!!! Your email has been verified. You would be automatically redirected to login page in 5 seconds. Else <a href='/login'> Click here </a>",
        linkExpired: "Email id does not match or the link has expired. Kindly try again...",
        waitForValidation: "Hold on... We are validating the email id...",
        invalidVerificationLonk: "Oooppsss... <br />Seems like the verification link is invalid. <br />",
        emailVerified: "Congrats...!!! Your email has been verified. Redirecting you to login page...",
        redirectionToLogin: "If not redirected in 5 seconds, <Link to='/login'>Click here to login</Link>",
        someErrorOccured: "Some Error Occured!",
        anErrorOccuredTryAgain: "An error occured.please try again.",
        loginSuccessful: "Login successful!",
        phone: "Phone",
        enterPhoneNumber: "Enter phone number",
        password: "Password",
        login: "Login",
        or: "OR",
        forgotPassword: "Forgot Password",
        signUp: "Sign Up",
        enterLocation: "Enter a location",
        failedSendingCode: "Failed sending code.",
        verificationCodeSent: "Verification code sent!",
        wrongVerificationCode: "Wrong Verification code!",
        emailAlreadyExists: "Email already exists.",
        phoneAlreadyExists: "Phone already exists.",
        accountCreatedSuccessfully: "Account created successfully!",
        createAccount: "Create Account",
        name: "Name",
        verificationCode: "Verification Code",
        unableToFetch: "Unable to fetch!",
        phoneVerificationCode: "Hi, Your phone verification code is",
        changeLanguage: "Switch to ",
        english: "English",
        arabic: "Arabic",
    },
    ar: {
        loggingOut: "تسجيل الخروج",
        Home: "الصفحة الرئيسية",
        Hello: "مرحبا",
        Register: "تسجيل",
        logout: "الخروج",
        Rides: "ركوب الخيل",
        Ride: "اركب",
        Settings: "الإعدادات",
        paymentStatus: "حالة السداد",
        totalDistance: "المسافة الكلية",
        boardingPoint: "نقطة الصعود",
        droppingPoint: "نقطة اسقاط",
        yourRides: "ركوب الخيل الخاص بك",
        distance: "مسافه: بعد",
        duration: "المدة الزمنية",
        editEmail: "اديث ايميل",
        subscriptions: "الاشتراكات",
        subscription: "اشتراك",
        price: "السعر",
        renewable: "قابل للتجديد",
        after: "بعد",
        days: "أيام",
        description: "وصف",
        callSupport: "دعم الاتصال",
        others: "الآخرين",
        driverMode: "وضع السائق",
        userMode: "وضع المستخدم",
        at: "في",
        meterShort: "M",
        kilimeterShort: "KM",
        fare: "أجرة",
        cash: "السيولة النقدية",
        Card: "بطاقة",
        book: "كتاب",
        bookRide: "كتاب ركوب",
        Time: "زمن",
        paymentMethod: "طريقة الدفع او السداد",
        rideBooked: "ركوب حجزها",
        rideCompleted: "اكتمل الركوب",
        paymentMarked: "دفع ملحوظ",
        onTheWay: "فى الطريق",
        navigateToRider: "انتقل إلى رايدر",
        startRide: "بدء الركوب",
        finishRide: "الانتهاء من ركوب",
        bookingID: "Booking ID",
        paymentReceived: "Payment Received",
        rideNotFinished: "Ride is not finished yet!",
        verifyYourEmailAddress: "Visit the following link to verify your email address.",
        confirm: "Confirm",
        on: "on",
        enterLocation: "أدخل الموقع",
        planNotFound: "Plan not found!",
        shouldContainOnlyAlphabets: "Should contain only alphabets",
        shouldContainOnlyNumbers: "Should contain only numbers",
        subscriptionPlansNotAvailable: "No subscription plans available!",
        seeNewRequests: "See new Requests",
        cancelRequest: "Cancel Request",
        subscribe: "Subscribe",
        unableToStartTheRide: "Unable to start the ride!",
        unableToGetSubscriptions: "Unable to get subscriptions!",
        unableToGetPlans: "Unable to get plans!",
        unableToSubscribe: "Unable to subscribe!",
        planSubscribed: "Plan Subscribed!",
        unableToFinishTheRide: "Unable to Finish the ride!",
        unabletoAcceptTheRide: "Unable to accept the ride!",
        unableToGetBooking: "Unable to get booking!",
        rideNotFinishedYet: "Ride not finished yet!",
        waitingForNearbyDriversToAcceptYourRideRequest: "Waiting for nearby drivers to accept your ride request",
        driverAcceptedYourRideRequest: "Driver accepted your ride request",
        unableToFetchDriversNearby: "unable to fetch drivers nearby",
        unableToFetchYourCurrentLocation: "Unable to fetch your current location",
        directionsRequestFailedDueTo: "Directions request failed due to",
        unableToCreateRequest: "Unable to create request!",
        unableToCancelRequest: "unable to cancel request",
        unableToMarkPaymentForTheRide: "Unable to mark payment for the ride!",
        emailVeried: "Congrats...!!! Your email has been verified. You would be automatically redirected to login page in 5 seconds. Else <a href='/login'> Click here </a>",
        linkExpired: "Email id does not match or the link has expired. Kindly try again...",
        waitForValidation: "Hold on... We are validating the email id...",
        invalidVerificationLonk: "Oooppsss... <br />Seems like the verification link is invalid. <br />",
        emailVerified: "Congrats...!!! Your email has been verified. Redirecting you to login page...",
        redirectionToLogin: "If not redirected in 5 seconds, <Link to='/login'>Click here to login</Link>",
        someErrorOccured: "Some Error Occured!",
        anErrorOccuredTryAgain: "An error occured.please try again.",
        loginSuccessful: "Login successful!",
        phone: "Phone",
        enterPhoneNumber: "Enter phone number",
        password: "Password",
        login: "Login",
        or: "OR",
        forgotPassword: "Forgot Password",
        signUp: "Sign Up",
        failedSendingCode: "Failed sending code.",
        verificationCodeSent: "Verification code sent!",
        wrongVerificationCode: "Wrong Verification code!",
        emailAlreadyExists: "Email already exists.",
        phoneAlreadyExists: "Phone already exists.",
        accountCreatedSuccessfully: "Account created successfully!",
        createAccount: "Create Account",
        name: "Name",
        verificationCode: "Verification Code",
        unableToFetch: "Unable to fetch!",
        phoneVerificationCode: "Hi, Your phone verification code is",
        changeLanguage: "التبديل إلى ",
        english: "الإنجليزية",
        arabic: "عربى",
    }
});

class LocalizationManager {
    constructor(lang) {
        this.strings = strings;
        this.language = lang;
        this.strings.setLanguage(lang);
        //this.getUser();
    }

    async getUser() {
        // var user = await Meteor.users.find({
        //     _id: Meteor.userId()
        // }, {
        //     fields: {
        //         emails: 1,
        //         profile: 1,
        //         admin: 1,
        //         demoUser: 1,
        //         _id: 1,
        //         createdAt: 1,
        //     },
        // });
        // console.log(user);
    }

    getLanguage() {
        return this.language;
    }

    toggle() {
        console.log(this.language == "en" ? "en=>ar" : "ar=>en");
        this.strings.setLanguage(this.language == "en" ? "ar" : "en");
        this.language = this.language == "en" ? "ar" : "en";
    }
}

var localizationManager = new LocalizationManager("ar");

export default localizationManager;